import { useEffect,useState } from 'react'; import { useNavigate,useSearchParams } from 'react-router-dom'; import apiClient from '@/api/client';
type Place={id:string;nombre:string};
const registrationFields: Array<[keyof Pick<RegistrationForm,'nombre'|'rut'|'email'|'telefono'|'alias'|'password'>,string]> = [['nombre','Nombre completo'],['rut','RUT'],['email','Correo electrónico'],['telefono','Teléfono'],['alias','Alias público'],['password','Contraseña']];
type RegistrationForm={nombre:string;rut:string;email:string;telefono:string;regionId:string;comunaId:string;alias:string;password:string;acceptsTerms:boolean};
const box:React.CSSProperties={background:'#fff',borderRadius:20,padding:28,boxShadow:'0 20px 60px rgba(8,25,72,.18)',width:'min(720px,calc(100vw - 32px))'};
export default function CapturerRegisterPage(){const nav=useNavigate();const [searchParams]=useSearchParams();const [regions,setRegions]=useState<Place[]>([]);const [communes,setCommunes]=useState<Place[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [pendingEmail,setPendingEmail]=useState(()=>searchParams.get('email')?.trim().toLowerCase()||'');const [code,setCode]=useState('');const [localVerificationCode,setLocalVerificationCode]=useState('');const [form,setForm]=useState({nombre:'',rut:'',email:'',telefono:'',regionId:'',comunaId:'',alias:'',password:'',acceptsTerms:false});
 useEffect(()=>{apiClient.get<Place[]>('/geografia/paises').then(async r=>{const chile=r.data.find(p=>p.nombre.trim().toLowerCase()==='chile')??r.data.find(p=>p.id.toUpperCase()==='CL');if(!chile)throw new Error('No se encontró Chile en el catálogo geográfico.');const regions=await apiClient.get<Place[]>(`/geografia/paises/${chile.id}/regiones`);setRegions(regions.data);}).catch(()=>setError('No se pudieron cargar las regiones.'));},[]);
 useEffect(()=>{setCommunes([]);setForm(f=>({...f,comunaId:''}));if(form.regionId)apiClient.get<Place[]>(`/geografia/regiones/${form.regionId}/comunas`).then(r=>setCommunes(r.data));},[form.regionId]);
 const update=(k:string,v:string|boolean)=>setForm(f=>({...f,[k]:v}));
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const response=await apiClient.post<{verificationCode?:string}>('/auth/register/capturer',{...form,regionId:Number(form.regionId),comunaId:Number(form.comunaId)});setLocalVerificationCode(response.data.verificationCode||'');setPendingEmail(form.email.trim().toLowerCase());}catch(e:any){setError(e.response?.data?.message||'No se pudo completar el registro.');}finally{setBusy(false);}}
 async function resend(){setBusy(true);setError('');try{const response=await apiClient.post<{verificationCode?:string}>('/auth/register/resend-code',{email:pendingEmail});setLocalVerificationCode(response.data.verificationCode||'');}catch(e:any){setError(e.response?.data?.message||'No se pudo reenviar el código.');}finally{setBusy(false);}}
 async function verify(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await apiClient.post('/auth/register/verify-email',{email:pendingEmail,code});nav('/login?type=capturer&verified=1',{replace:true});}catch(e:any){setError(e.response?.data?.message||'Código inválido o vencido.');}finally{setBusy(false);}}
 return <main style={{minHeight:'100vh',background:'linear-gradient(135deg,#061846,#0b3b91)',display:'grid',placeItems:'center',padding:24,fontFamily:'Inter,system-ui,sans-serif'}}><section style={box}><button type="button" onClick={()=>nav('/login?type=capturer')} style={{border:0,background:'none',color:'#2563eb',cursor:'pointer'}}>← Volver al acceso</button><div style={{textAlign:'center',marginBottom:22}}><img src="/assets/repuestop-logo.jpg" alt="RepuesTop" style={{height:72}}/><h1 style={{margin:'8px 0 4px',color:'#10204b'}}>Postula como captador</h1><p style={{margin:0,color:'#64748b'}}>Crea tu cuenta. El equipo revisará la solicitud antes de habilitar tu panel.</p></div>{error&&<p style={{background:'#fef2f2',color:'#b91c1c',padding:12,borderRadius:10}}>{error}</p>}{pendingEmail?<form onSubmit={verify} style={{display:'grid',gap:14,maxWidth:420,margin:'auto'}}>{localVerificationCode&&<p style={{margin:0,padding:12,borderRadius:10,background:'#eff6ff',color:'#1d4ed8'}}>Código local: <strong>{localVerificationCode}</strong></p>}<label>Código enviado a {pendingEmail}<input value={code} onChange={e=>setCode(e.target.value)} required maxLength={6} style={input}/></label><button type="button" onClick={resend} disabled={busy} style={{border:0,background:'none',color:'#155eef',cursor:'pointer'}}>¿Venció o no llegó? Reenviar código</button><button disabled={busy} style={primary}>{busy?'Verificando…':'Verificar correo'}</button></form>:<form onSubmit={submit} style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14}}>{registrationFields.map(([k,l])=><label key={k} style={label}>{l}<input type={k==='email'?'email':k==='password'?'password':'text'} value={form[k]} onChange={e=>update(k,e.target.value)} required style={input}/></label>)}<label style={label}>Región<select value={form.regionId} onChange={e=>update('regionId',e.target.value)} required style={input}><option value="">Selecciona región</option>{regions.map(r=><option key={r.id} value={r.id}>{r.nombre}</option>)}</select></label><label style={label}>Comuna<select value={form.comunaId} onChange={e=>update('comunaId',e.target.value)} required disabled={!form.regionId} style={input}><option value="">Selecciona comuna</option>{communes.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label style={{gridColumn:'1/-1',display:'flex',gap:9,color:'#475569'}}><input type="checkbox" checked={form.acceptsTerms} onChange={e=>update('acceptsTerms',e.target.checked)} required/> Acepto los términos y el tratamiento de mis datos para esta postulación.</label><button disabled={busy} style={{...primary,gridColumn:'1/-1'}}>{busy?'Enviando…':'Enviar postulación'}</button></form>}</section></main>}
const label:React.CSSProperties={display:'grid',gap:6,color:'#334155',fontWeight:600,fontSize:14};const input:React.CSSProperties={padding:'11px 12px',border:'1px solid #cbd5e1',borderRadius:9,fontSize:15,background:'#fff'};const primary:React.CSSProperties={padding:12,border:0,borderRadius:10,background:'#155eef',color:'#fff',fontWeight:700,fontSize:15,cursor:'pointer'};
