import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import * as api from '@/api/capturers';
import { useAuth } from '@/context/AuthContext';
import { Role } from '@/types/auth';
import type { CapturerConfig } from '@/types/capturer';

export default function CapturerValidationTab(){
  const qc=useQueryClient(); const {user}=useAuth(); const [reason,setReason]=useState<Record<number,string>>({}); const [config,setConfig]=useState<CapturerConfig|null>(null);
  const query=useQuery({queryKey:['capturer-validations'],queryFn:api.listCapturers});
  const configQuery=useQuery({queryKey:['capturer-config'],queryFn:api.getCapturerConfig,enabled:user?.role===Role.SUPER_ADMIN});
  useEffect(()=>{if(configQuery.data)setConfig(configQuery.data)},[configQuery.data]);
  const mutation=useMutation({mutationFn:async({id,action}:{id:number;action:'approve'|'reject'})=>action==='approve'?api.approveCapturer(id):api.rejectCapturer(id,reason[id]?.trim()||'Solicitud rechazada por el equipo de validación.'),onSuccess:()=>qc.invalidateQueries({queryKey:['capturer-validations']})});
  const configMutation=useMutation({mutationFn:api.saveCapturerConfig,onSuccess:data=>{setConfig(data);qc.invalidateQueries({queryKey:['capturer-config']})}});
  if(query.isLoading)return <div style={empty}>Cargando solicitudes de captadores…</div>;
  return <div style={{display:'grid',gap:14}}>{config&&<article style={{...card,borderTop:'4px solid #2563eb'}}><h3 style={{marginTop:0}}>Puntaje y comisiones</h3><div style={{display:'grid',gridTemplateColumns:'repeat(5,minmax(120px,1fr))',gap:9}}>{([['puntosCasaAprobada','Puntos por casa',1],['puntosServicioPrimeraCompra','Puntos primer pago',1],['pesosPorPunto','Pesos por punto',1],['comisionCasa','Comisión casa',0.01],['comisionPublicidad','Comisión publicidad',0.01]] as const).map(([key,label,step])=><label key={key} style={{display:'grid',gap:5,fontSize:12,fontWeight:650}}>{label}<input type="number" min="0" max={key.startsWith('comision')?1:undefined} step={step} value={config[key]} onChange={e=>setConfig(v=>v?{...v,[key]:Number(e.target.value)}:v)} style={input}/></label>)}</div><button style={{...approve,marginTop:10,background:'#2563eb'}} disabled={configMutation.isPending} onClick={()=>configMutation.mutate(config)}>Guardar configuración</button></article>}{query.data?.length===0&&<div style={empty}>No hay solicitudes de captadores.</div>}{query.data?.map(c=><article key={c.id} style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h3 style={{margin:'0 0 5px'}}>{c.nombre} <span style={{color:'#2563eb'}}>@{c.alias}</span></h3><div style={muted}>{c.rut} · {c.email} · {c.telefono}</div><div style={muted}>{c.comuna}, {c.region} · {new Date(c.createdAt).toLocaleDateString('es-CL')}</div></div><span style={pill(c.estado)}>{c.estado}</span></div>{c.estado==='PENDIENTE'&&<div style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:9,marginTop:14}}><input value={reason[c.id]||''} onChange={e=>setReason(v=>({...v,[c.id]:e.target.value}))} placeholder="Motivo si se rechaza" style={input}/><button disabled={mutation.isPending} onClick={()=>mutation.mutate({id:c.id,action:'approve'})} style={approve}>Aprobar</button><button disabled={mutation.isPending} onClick={()=>mutation.mutate({id:c.id,action:'reject'})} style={reject}>Rechazar</button></div>}{c.motivoRechazo&&<p style={{...muted,marginBottom:0}}>Motivo: {c.motivoRechazo}</p>}</article>)}</div>;
}
const card:React.CSSProperties={background:'#fff',border:'1px solid #e2e8f0',borderRadius:14,padding:18,boxShadow:'0 6px 20px rgba(15,23,42,.05)'};
const empty:React.CSSProperties={...card,textAlign:'center',color:'#64748b'}; const muted:React.CSSProperties={color:'#64748b',fontSize:13,marginTop:4};
const input:React.CSSProperties={padding:'10px 12px',border:'1px solid #cbd5e1',borderRadius:8}; const approve:React.CSSProperties={padding:'9px 14px',border:0,borderRadius:8,background:'#16a34a',color:'#fff',fontWeight:700,cursor:'pointer'}; const reject:React.CSSProperties={...approve,background:'#dc2626'};
const pill=(state:string):React.CSSProperties=>({height:'fit-content',padding:'5px 9px',borderRadius:999,fontSize:12,fontWeight:700,background:state==='APROBADO'?'#dcfce7':state==='RECHAZADO'?'#fee2e2':'#fef3c7',color:state==='APROBADO'?'#166534':state==='RECHAZADO'?'#991b1b':'#92400e'});
