import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import * as api from '@/api/capturers';

export default function ServiceValidationTab(){
 const qc=useQueryClient();const [notes,setNotes]=useState<Record<number,string>>({});const query=useQuery({queryKey:['automotive-service-validations'],queryFn:api.listServices});const mutation=useMutation({mutationFn:({id,action}:{id:number;action:'approve'|'request-correction'|'reject'})=>api.decideService(id,action,notes[id]||''),onSuccess:()=>qc.invalidateQueries({queryKey:['automotive-service-validations']})});
 if(query.isLoading)return <div style={empty}>Cargando expedientes de servicios…</div>;
 return <div style={{display:'grid',gap:14}}>{query.data?.length===0&&<div style={empty}>No hay expedientes de servicios automotrices.</div>}{query.data?.map(s=><article style={card} key={s.id}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h3 style={{margin:'0 0 5px'}}>{s.nombreNegocio}</h3><div style={muted}>{s.rutNegocio} · Responsable: {s.responsable}</div><div style={muted}>{s.usuarioNombre} ({s.usuarioRol}) · {s.usuarioEmail}</div><div style={muted}>{s.comuna}, {s.region}{s.captadorAlias?` · Referido por @${s.captadorAlias}`:''}</div></div><span style={pill(s.estado)}>{s.estado.replace('_',' ')}</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8,marginTop:14}}>{([['Identidad / RUT',s.documentoIdentidadNombre,'identidad'],['Inicio actividades SII',s.inicioActividadesNombre,'inicio-actividades'],['Patente municipal',s.patenteMunicipalNombre,'patente-municipal']] as const).map(([label,name,tipo])=><div style={doc} key={label}><strong>{label}</strong><span>{name||'No cargado'}</span>{name&&<button style={link} onClick={()=>void api.downloadServiceDocument(s.id,tipo,name)}>Ver documento</button>}</div>)}</div>{['PENDIENTE','POR_CORREGIR'].includes(s.estado)&&<><textarea value={notes[s.id]||''} onChange={e=>setNotes(v=>({...v,[s.id]:e.target.value}))} placeholder="Observaciones o correcciones" style={{...input,width:'100%',boxSizing:'border-box',marginTop:12}}/><div style={{display:'flex',gap:8,marginTop:9,justifyContent:'flex-end'}}><button style={approve} onClick={()=>mutation.mutate({id:s.id,action:'approve'})}>Aprobar</button><button style={correct} onClick={()=>mutation.mutate({id:s.id,action:'request-correction'})}>Solicitar corrección</button><button style={reject} onClick={()=>mutation.mutate({id:s.id,action:'reject'})}>Rechazar</button></div></>}</article>)}</div>;
}
const card:React.CSSProperties={background:'#fff',border:'1px solid #e2e8f0',borderRadius:14,padding:18,boxShadow:'0 6px 20px rgba(15,23,42,.05)'};const empty:React.CSSProperties={...card,textAlign:'center',color:'#64748b'};const muted:React.CSSProperties={color:'#64748b',fontSize:13,marginTop:4};const doc:React.CSSProperties={display:'grid',gap:5,padding:10,borderRadius:9,background:'#f8fafc',fontSize:12,color:'#475569'};const input:React.CSSProperties={padding:'10px 12px',border:'1px solid #cbd5e1',borderRadius:8};const approve:React.CSSProperties={padding:'9px 14px',border:0,borderRadius:8,background:'#16a34a',color:'#fff',fontWeight:700,cursor:'pointer'};const correct:React.CSSProperties={...approve,background:'#d97706'};const reject:React.CSSProperties={...approve,background:'#dc2626'};const pill=(state:string):React.CSSProperties=>({height:'fit-content',padding:'5px 9px',borderRadius:999,fontSize:12,fontWeight:700,background:state==='APROBADO'?'#dcfce7':state==='RECHAZADO'?'#fee2e2':'#fef3c7',color:state==='APROBADO'?'#166534':state==='RECHAZADO'?'#991b1b':'#92400e'});
const link:React.CSSProperties={border:0,background:'none',color:'#2563eb',padding:0,textAlign:'left',fontWeight:700,cursor:'pointer'};
